# Generated by Django 3.1.7 on 2021-12-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addVote', '0003_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
